- name: Add the user srvc-ansible
  ansible.builtin.user:
    name: srvc-rke
    comment: User rke
    uid: 2001
    groups: docker

- name: make direcotry
  file:
    path: "/home/srvc-rke/.ssh"
    state: directory

- name: copy authorized_keys
  ansible.builtin.copy:
    src: ~/ssh/rke.pub
    dest: /home/srvc-rke/.ssh/authorized_keys
    owner: srvc-rke
    group: srvc-rke
    mode: '600'
