- name: Install utils
  yum: 
    name: yum-utils

- name: Add repository Docker
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install a list of packages docker
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce 
    - docker-ce-cli
    - containerd.io

- name: Start service Docker and enable
  ansible.builtin.service:
    name: docker
    state: started 
    enabled: yes
