- name: Create file repo Docker
  ansible.builtin.file:
   path: /etc/yum.repos.d/docker.repo
   state: touch
   mode: '0644'

- name: Install utils
  yum: yum-utils

- name: Add repository Docker
  yum_repository:
    name: docker
    description: Docker YUM repo
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: Install a list of packages docker
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce 
    - docker-ce-cli
    - containerd.io 
